sonar.organization=rubenlr
sonar.projectKey=rubenlr_workpot

sonar.sources=crates
sonar.tests=crates
sonar.test.inclusions=**/tests/**

sonar.exclusions=**/target/**,**/*.rs.bk

sonar.rust.lcov.reportPaths=lcov.info
sonar.sourceEncoding=UTF-8
