ALTER TABLE repos ADD COLUMN branch TEXT;
ALTER TABLE repos ADD COLUMN is_dirty INTEGER;
ALTER TABLE repos ADD COLUMN ahead INTEGER;
ALTER TABLE repos ADD COLUMN behind INTEGER;
ALTER TABLE repos ADD COLUMN git_refreshed_at INTEGER;
ALTER TABLE repos ADD COLUMN git_state_error TEXT;
